version: '3.3'

volumes:
  pg_data_foodgram:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file:
      - ../.env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  backend:
    image: vangogh67/foodgram_backend
    build: ../backend
    volumes:
      - static:/static
      - media:/app/media
    env_file:
      - ../.env
    depends_on:
        - db
    restart: always

  frontend:
    image: vangogh67/foodgram_frontend
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media
    depends_on:
      - backend
      - frontend
